{"timestamp":"2025-07-14T11:50:55.397658","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-14T11:50:55.398365","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/dag_analisis.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-14T11:50:55.445649Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-14T11:50:55.446374Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-14T11:50:55.447017Z","level":"info","event":"Current task name:detectar_desviacion","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-14T11:50:55.447638Z","level":"info","event":"Dag name:a2","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-14T11:50:55.447834Z","level":"info","event":"franja 8 - 10","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-14T11:50:55.447988Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-14T11:50:55.448135Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-14T11:50:55.448281Z","level":"info","event":"Task:<Task(PythonOperator): detectar_desviacion>","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-14T11:50:55.448427Z","level":"info","event":"Failure caused by syntax error at or near \"=>\"","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-14T11:50:55.448570Z","level":"info","event":"LINE 6: ...                       EXTRACT(HOUR FROM timestamp) =>8 and","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-14T11:50:55.448714Z","level":"info","event":"                                                               ^","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-14T11:50:55.448855Z","level":"info","event":"","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-14T11:50:55.421132","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"SyntaxError","exc_value":"syntax error at or near \"=>\"\nLINE 6: ...                       EXTRACT(HOUR FROM timestamp) =>8 and \n                                                               ^\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":867,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1159,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/dag_analisis.py","lineno":106,"name":"detectar_desviacion"}],"is_group":false,"exceptions":[]}]}
