{"timestamp":"2025-07-14T12:10:36.423605","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-14T12:10:36.424445","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/dag_analisis.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-14T12:10:36.480052Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-14T12:10:36.480355Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-14T12:10:36.480541Z","level":"info","event":"Current task name:detectar_desviacion","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-14T12:10:36.480726Z","level":"info","event":"Dag name:a2","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-14T12:10:36.480885Z","level":"info","event":"franja 8 - 10","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-14T12:10:36.481048Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-14T12:10:36.481204Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-14T12:10:36.481370Z","level":"info","event":"Task:<Task(PythonOperator): detectar_desviacion>","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-14T12:10:36.481546Z","level":"info","event":"Failure caused by syntax error at or near \"status\"","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-14T12:10:36.481716Z","level":"info","event":"LINE 8:                                         status = 'valido' an...","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-14T12:10:36.481885Z","level":"info","event":"                                                ^","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-14T12:10:36.482059Z","level":"info","event":"","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-14T12:10:36.456393","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"SyntaxError","exc_value":"syntax error at or near \"status\"\nLINE 8:                                         status = 'valido' an...\n                                                ^\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":867,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1159,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/dag_analisis.py","lineno":103,"name":"detectar_desviacion"}],"is_group":false,"exceptions":[]}]}
