{"timestamp":"2025-07-11T20:00:42.163839","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-11T20:00:42.168651","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/test1.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-11T20:00:42.264423Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T20:00:42.264838Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T20:00:42.265107Z","level":"info","event":"Current task name:generar_registros_dispositivos","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T20:00:42.265341Z","level":"info","event":"Dag name:tutorial-p","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T20:09:34.120250","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"OperationalError","exc_value":"connection to server at \"postgres-datos\" (172.18.0.4), port 5432 failed: FATAL:  the database system is shutting down\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":867,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1159,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/test1.py","lineno":113,"name":"generar_registros_dispositivos"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py","lineno":122,"name":"connect"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-11T20:09:34.124061Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T20:09:34.124278Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T20:09:34.124443Z","level":"info","event":"Task:<Task(PythonOperator): generar_registros_dispositivos>","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T20:09:34.124603Z","level":"info","event":"Failure caused by connection to server at \"postgres-datos\" (172.18.0.4), port 5432 failed: FATAL:  the database system is shutting down","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T20:09:34.124763Z","level":"info","event":"","chan":"stdout","logger":"task"}
